export const NUMERIC_DIGITS = "NUMERIC_DIGITS";
export const NUMERIC_DIGIT_ZERO = "NUMERIC_DIGIT_ZERO";
export const MANEGE_OPERATORS = "MANEGE_OPERATORS";
export const SHOW_RESULT = "SHOW_RESULT";
export const FLOAT_VALUE_CREATE = "FLOAT_VALUE_CREATE";
export const CHANGE_TO_POS_NEG = "CHANGE_TO_POS_NEG";
export const CLEAR_COMPLETELY = "CLEAR_COMPLETELY";
export const BACKSPACE_PRESSED = "BACKSPACE_PRESSED";
