export const NUMERIC_DIGITS = "NUMERIC_DIGITS";
export const MANEGE_OPERATORS = "MANEGE_OPERATORS";
export const FLOAT_VALUE_CREATE = "FLOAT_VALUE_CREATE";
export const CHANGE_TO_POS_NEG = "CHANGE_TO_POS_NEG";
export const CLEAR_COMPLETELY = "CLEAR_COMPLETELY";
export const PERCENTAGE_MODULE = "PERCENTAGE_MODULE";
